import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(packageDir, '..', '..', '..');
const sourceSvgPath = resolve(repoRoot, 'icons.svg');
const targetSvgPath = resolve(packageDir, 'src', 'icons.svg');
const targetNamesPath = resolve(packageDir, 'src', 'names.ts');

const svg = await readFile(sourceSvgPath, 'utf8');
const symbolMatches = Array.from(
  svg.matchAll(/<symbol\s+id="([^"]+)"[^>]*>([\s\S]*?)<\/symbol>/g),
);
const names = symbolMatches.map((match) => match[1]);
const uniqueNames = Array.from(new Set(names));

if (names.length === 0) {
  throw new Error(`No SVG symbols found in ${sourceSvgPath}`);
}

if (uniqueNames.length !== names.length) {
  const duplicates = names.filter((name, index) => names.indexOf(name) !== index);
  throw new Error(`Duplicate SVG symbol ids: ${Array.from(new Set(duplicates)).join(', ')}`);
}

await mkdir(dirname(targetSvgPath), { recursive: true });
await writeFile(targetSvgPath, svg);

const namesSource = `// Generated from ../../../icons.svg by scripts/generate-icons.mjs.\n` +
  `// Do not edit this file by hand.\n\n` +
  `export const iconNames = ${JSON.stringify(uniqueNames, null, 2)} as const;\n\n` +
  `export type IconName = typeof iconNames[number];\n`;

await writeFile(targetNamesPath, namesSource);

const symbolEntries = symbolMatches.map((match) => [match[1], match[2].trim()]);
const symbolsSource = `// Generated from ../../../icons.svg by scripts/generate-icons.mjs.\n` +
  `// Do not edit this file by hand.\n\n` +
  `import type { IconName } from './names';\n\n` +
  `export const iconSymbols = ${JSON.stringify(Object.fromEntries(symbolEntries), null, 2)} as const satisfies Record<IconName, string>;\n`;

await writeFile(resolve(packageDir, 'src', 'symbols.ts'), symbolsSource);

console.log(`Synced ${uniqueNames.length} ChuFix icons.`);
