export const site = {
  title: 'ChuFix UI',
  nameZh: '础件',
  tagline: '初见即用的基础组件库',
  description: '础件 ChuFix UI · 初见即用的基础组件库，Vue 3 与 React 双框架同源，纯 HTML/JS 项目也能直接用 CSS 类名。',
  github: 'https://github.com/chenqi92/chufix',
  docsRepo: 'https://github.com/chenqi92/chufix-docs',
  version: '0.0.1',
  status: {
    label: '开发预览',
    updatedAt: '2026-05-09',
    npmPublished: false,
    announcementTitle: 'ChuFix UI 正在持续更新',
    announcement:
      '当前文档展示的是开发预览版 API，组件库尚未发布到 npm 公共库；示例和能力会继续补齐，安装说明会在公共包发布后同步更新。',
  },
};

export interface SidebarLink {
  label: string;
  href: string;
}

export interface SidebarGroup {
  label: string;
  items: SidebarLink[];
}

export const sidebar: SidebarGroup[] = [
  {
    label: '开始',
    items: [
      { label: '介绍', href: '/' },
      { label: '安装', href: '/getting-started/installation/' },
      { label: '纯 HTML / JS 用法', href: '/getting-started/vanilla/' },
      { label: '主题与 Tokens', href: '/getting-started/theming/' },
    ],
  },
  {
    label: '组件总览',
    items: [
      { label: '所有组件', href: '/components/' },
      { label: 'Icon 图标', href: '/components/icon/' },
    ],
  },
  {
    label: '表单',
    items: [
      { label: 'Button 按钮', href: '/components/button/' },
      { label: 'IconButton 图标按钮', href: '/components/iconbutton/' },
      { label: 'SplitButton 分裂按钮', href: '/components/splitbutton/' },
      { label: 'Input 输入框', href: '/components/input/' },
      { label: 'VariableAwareInput 变量输入', href: '/components/variableinput/' },
      { label: 'PasswordStrength 密码强度', href: '/components/passwordstrength/' },
      { label: 'PhoneInput 电话号码', href: '/components/phoneinput/' },
      { label: 'Textarea 多行', href: '/components/textarea/' },
      { label: 'Select 选择器', href: '/components/select/' },
      { label: 'Switch 开关', href: '/components/switch/' },
      { label: 'Checkbox 复选框', href: '/components/checkbox/' },
      { label: 'Radio 单选框', href: '/components/radio/' },
      { label: 'SearchInput 搜索框', href: '/components/searchinput/' },
      { label: 'NumberInput 数字输入', href: '/components/numberinput/' },
      { label: 'Slider 滑块', href: '/components/slider/' },
      { label: 'RangeSlider 范围滑块', href: '/components/rangeslider/' },
      { label: 'ColorSwatch 颜色块', href: '/components/colorswatch/' },
      { label: 'InputGroup 输入组合', href: '/components/inputgroup/' },
      { label: 'OtpInput 一次性密码', href: '/components/otp/' },
      { label: 'Form 表单', href: '/components/form/' },
      { label: 'Combobox 组合选择', href: '/components/combobox/' },
      { label: 'TagInput 标签输入', href: '/components/taginput/' },
      { label: 'Dropzone 文件拖拽', href: '/components/dropzone/' },
      { label: 'FilePicker 文件选择', href: '/components/filepicker/' },
      { label: 'ColorPicker 颜色选择', href: '/components/colorpicker/' },
      { label: 'DatePicker 日期选择', href: '/components/datepicker/' },
      { label: 'DateRangePicker 日期范围', href: '/components/daterangepicker/' },
      { label: 'KVEditor 键值编辑器', href: '/components/kveditor/' },
      { label: 'Mention 提及输入', href: '/components/mention/' },
      { label: 'Cascader 级联选择', href: '/components/cascader/' },
      { label: 'TimePicker 时间选择', href: '/components/timepicker/' },
      { label: 'Transfer 穿梭框', href: '/components/transfer/' },
      { label: 'TimeRangePicker 时间范围', href: '/components/timerangepicker/' },
    ],
  },
  {
    label: '容器',
    items: [
      { label: 'Card 卡片', href: '/components/card/' },
      { label: 'PageHeader 页头', href: '/components/pageheader/' },
      { label: 'AppShell 应用脚手架', href: '/components/appshell/' },
      { label: 'Splitter 分隔面板', href: '/components/splitter/' },
      { label: 'Toolbar 工具栏', href: '/components/toolbar/' },
      { label: 'Calendar 日历', href: '/components/calendar/' },
    ],
  },
  {
    label: '数据展示',
    items: [
      { label: 'Tag 标签', href: '/components/tag/' },
      { label: 'Badge 徽标', href: '/components/badge/' },
      { label: 'ProtocolBadge 协议徽标', href: '/components/protocolbadge/' },
      { label: 'MethodBadge HTTP 方法', href: '/components/methodbadge/' },
      { label: 'StatusCodeBadge 状态码', href: '/components/statuscodebadge/' },
      { label: 'StatusIllustration 状态插图', href: '/components/statusillustration/' },
      { label: 'Avatar 头像', href: '/components/avatar/' },
      { label: 'List 列表', href: '/components/list/' },
      { label: 'DescriptionList 描述列表', href: '/components/descriptionlist/' },
      { label: 'Stat / KPI 指标', href: '/components/stat/' },
      { label: 'Table 表格', href: '/components/table/' },
      { label: 'DataGrid 数据网格', href: '/components/datagrid/' },
      { label: 'TreeView 树形列表', href: '/components/treeview/' },
      { label: 'Kbd 键盘按键', href: '/components/kbd/' },
      { label: 'Link 链接', href: '/components/link/' },
      { label: 'Code 代码', href: '/components/code/' },
      { label: 'AspectRatio 宽高比', href: '/components/aspectratio/' },
      { label: 'Rating 评分', href: '/components/rating/' },
      { label: 'Toc 目录锚点', href: '/components/toc/' },
      { label: 'ScrollArea 滚动容器', href: '/components/scrollarea/' },
      { label: 'JsonViewer JSON 浏览', href: '/components/jsonviewer/' },
      { label: 'JsonDiff JSON 对比', href: '/components/jsondiff/' },
      { label: 'Kanban 看板', href: '/components/kanban/' },
      { label: 'Image 图片', href: '/components/image/' },
      { label: 'Carousel 轮播', href: '/components/carousel/' },
      { label: 'Statistic 统计数值', href: '/components/statistic/' },
      { label: 'Timeline 时间轴', href: '/components/timeline/' },
      { label: 'Marquee 跑马灯', href: '/components/marquee/' },
      { label: 'ImagePreview 大图预览', href: '/components/imagepreview/' },
      { label: 'Highlight 文本高亮', href: '/components/highlight/' },
      { label: 'TextEllipsis 多行省略', href: '/components/textellipsis/' },
      { label: 'CountDown 倒计时', href: '/components/countdown/' },
      { label: 'CalendarHeatmap 活跃热力', href: '/components/calendarheatmap/' },
      { label: 'QRCode 二维码', href: '/components/qrcode/' },
    ],
  },
  {
    label: '导航',
    items: [
      { label: 'Tabs 标签页', href: '/components/tabs/' },
      { label: 'SegmentedControl 分段控件', href: '/components/segmented/' },
      { label: 'Breadcrumb 面包屑', href: '/components/breadcrumb/' },
      { label: 'Pagination 分页', href: '/components/pagination/' },
      { label: 'Dropdown 下拉菜单', href: '/components/dropdown/' },
      { label: 'Stepper 步骤指示', href: '/components/stepper/' },
      { label: 'Sidebar 侧栏', href: '/components/sidebar/' },
      { label: 'NavMenu 主导航', href: '/components/navmenu/' },
      { label: 'Anchor 锚点导航', href: '/components/anchor/' },
    ],
  },
  {
    label: '反馈与覆盖层',
    items: [
      { label: 'Modal 弹窗', href: '/components/modal/' },
      { label: 'ConfirmDialog 确认弹窗', href: '/components/confirmdialog/' },
      { label: 'Tooltip 提示', href: '/components/tooltip/' },
      { label: 'HoverCard 悬停卡片', href: '/components/hovercard/' },
      { label: 'Toast 通知', href: '/components/toast/' },
      { label: 'Snackbar 底部通知', href: '/components/snackbar/' },
      { label: 'Alert 警示', href: '/components/alert/' },
      { label: 'Skeleton 骨架屏', href: '/components/skeleton/' },
      { label: 'Drawer 抽屉', href: '/components/drawer/' },
      { label: 'Popover 弹出层', href: '/components/popover/' },
      { label: 'ContextMenu 右键菜单', href: '/components/contextmenu/' },
      { label: 'CommandPalette 命令面板', href: '/components/commandpalette/' },
      { label: 'Banner 全宽提示', href: '/components/banner/' },
      { label: 'Result 结果页', href: '/components/result/' },
    ],
  },
  {
    label: '布局与状态',
    items: [
      { label: 'Divider 分割线', href: '/components/divider/' },
      { label: 'Empty 空状态', href: '/components/empty/' },
      { label: 'Progress 进度', href: '/components/progress/' },
      { label: 'Spinner 加载', href: '/components/spinner/' },
      { label: 'Accordion 折叠面板', href: '/components/accordion/' },
      { label: 'BackTop 返回顶部', href: '/components/backtop/' },
      { label: 'Affix 固钉', href: '/components/affix/' },
      { label: 'Watermark 水印', href: '/components/watermark/' },
      { label: 'FloatButton 悬浮按钮', href: '/components/floatbutton/' },
      { label: 'InfiniteScroll 无限滚动', href: '/components/infinitescroll/' },
      { label: 'Tour 新手引导', href: '/components/tour/' },
    ],
  },
  {
    label: '编辑器',
    items: [
      { label: 'CodeEditor 代码编辑', href: '/components/codeeditor/' },
      { label: 'DiffEditor 文本对比', href: '/components/diffeditor/' },
      { label: 'MarkdownEditor Markdown', href: '/components/markdowneditor/' },
      { label: 'RegexBuilder 正则构建', href: '/components/regexbuilder/' },
      { label: 'AnsiText ANSI 文本', href: '/components/ansitext/' },
    ],
  },
  {
    label: '系统壳层',
    items: [
      { label: 'TitleBar 标题栏', href: '/components/titlebar/' },
      { label: 'StatusBar 状态栏', href: '/components/statusbar/' },
      { label: 'MenuBar 菜单栏', href: '/components/menubar/' },
      { label: 'NotificationCenter 通知中心', href: '/components/notificationcenter/' },
      { label: 'GlobalSearch 全局搜索', href: '/components/globalsearch/' },
    ],
  },
  {
    label: '多窗口布局',
    items: [
      { label: 'DockLayout 多面板布局', href: '/components/docklayout/' },
      { label: 'DetachedPanel 浮动面板', href: '/components/detachedpanel/' },
      { label: 'FloatingInspector 浮动检查器', href: '/components/floatinginspector/' },
      { label: 'TearOffTabs 可撕离 Tab', href: '/components/tearofftab/' },
    ],
  },
  {
    label: '数据可视化',
    items: [
      { label: 'Sparkline 缩略走势', href: '/components/sparkline/' },
      { label: 'LineChart 折线图', href: '/components/linechart/' },
      { label: 'AreaChart 面积图', href: '/components/areachart/' },
      { label: 'BarChart 柱状图', href: '/components/barchart/' },
      { label: 'Histogram 直方图', href: '/components/histogram/' },
      { label: 'StackedBar100 占比柱', href: '/components/stackedbar100/' },
      { label: 'BulletChart 子弹图', href: '/components/bulletchart/' },
      { label: 'CandlestickChart K 线图', href: '/components/candlestickchart/' },
      { label: 'DonutChart 环形图', href: '/components/donutchart/' },
      { label: 'FunnelChart 漏斗图', href: '/components/funnelchart/' },
      { label: 'Treemap 矩形树图', href: '/components/treemap/' },
      { label: 'SankeyDiagram 流向图', href: '/components/sankeydiagram/' },
      { label: 'ScatterPlot 散点图', href: '/components/scatterplot/' },
      { label: 'BoxPlot 箱线图', href: '/components/boxplot/' },
      { label: 'RadarChart 雷达图', href: '/components/radarchart/' },
      { label: 'RidgePlot 密度脊图', href: '/components/ridgeplot/' },
      { label: 'Gauge 仪表盘', href: '/components/gauge/' },
      { label: 'MetricCard 指标卡', href: '/components/metriccard/' },
      { label: 'TimingBar 请求瀑布', href: '/components/timingbar/' },
      { label: 'LatencyHeatmap 延迟热力图', href: '/components/latencyheatmap/' },
      { label: 'ConnectionGraph 连接图', href: '/components/connectiongraph/' },
      { label: 'ChartCrosshair 十字线', href: '/components/chartcrosshair/' },
      { label: 'ChartToolbar 图表工具栏', href: '/components/charttoolbar/' },
    ],
  },
  {
    label: '模版 / 页面模块',
    items: [
      { label: 'ProtocolPane 协议面板', href: '/components/protocolpane/' },
      { label: 'NetworkPane 网络面板', href: '/components/networkpane/' },
      { label: 'SqlWorkbench SQL 工作台', href: '/components/sqlworkbench/' },
      { label: 'TerminalPane 终端面板', href: '/components/terminalpane/' },
      { label: 'CrashPane 崩溃面板', href: '/components/crashpane/' },
      { label: 'PluginPane 插件面板', href: '/components/pluginpane/' },
      { label: 'DomainPane API 调试', href: '/components/domainpane/' },
      { label: 'OnboardingFlow 引导流', href: '/components/onboardingflow/' },
    ],
  },
];
